-- 문제 1번
SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE
				   FROM EMPLOYEE
				   WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';

-- 문제 2번
SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY = (SELECT MAX(SALARY)
				FROM EMPLOYEE
				WHERE EXTRACT(YEAR FROM HIRE_DATE) >= 2000);
				
-- 문제 3번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
							   FROM EMPLOYEE
							   WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';

-- 문제 4번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
							   FROM EMPLOYEE
							   WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000);

-- 문제 5번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) = (SELECT DEPT_CODE, MANAGER_ID
								 FROM EMPLOYEE
								 WHERE SUBSTR(EMP_NO, 1, 2) = 77
								 AND SUBSTR(EMP_NO, 8, 1) IN (2, 4));
								 
-- 문제 6번
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE MAIN
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEE SUB
				   WHERE (ENT_YN = 'N' AND SUB.DEPT_CODE = MAIN.DEPT_CODE)
				   OR (ENT_YN = 'N' AND MAIN.DEPT_CODE IS NULL AND SUB.DEPT_CODE IS NULL))
ORDER BY HIRE_DATE;
								
-- 문제 7번
SELECT EMP_ID, EMP_NAME, JOB_NAME,
	FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO, 1, 6)))/12) AS 나이,
	TO_CHAR(NVL((SALARY+(SALARY*BONUS))*12, (SALARY*12)), 'L999,999,999') AS 보너스포함연봉
FROM EMPLOYEE MAIN
JOIN JOB J ON (MAIN.JOB_CODE = J.JOB_CODE)
WHERE EMP_NO = (SELECT MAX(EMP_NO)
				FROM EMPLOYEE SUB
				WHERE SUB.JOB_CODE = MAIN.JOB_CODE)
ORDER BY 나이 DESC;
