-- 1번 문제
SELECT EMP_NAME "사원명",
	ABS(CEIL(HIRE_DATE-SYSDATE)) "근무일수1",
	CEIL(SYSDATE-HIRE_DATE)-1 "근무일수2"
FROM EMPLOYEE;

-- 2번 문제
SELECT EMP_ID, EMP_NAME, EMAIL, PHONE
FROM EMPLOYEE
WHERE MOD(TO_NUMBER(EMP_ID), 2) = 1;

-- 3번 문제
SELECT *
FROM EMPLOYEE
WHERE (SYSDATE-HIRE_DATE)/365 >= 20;

-- 4번 문제
SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 8), 14, '*') AS 주민등록번호
FROM EMPLOYEE;

-- 5번 문제
SELECT EMP_NAME, JOB_CODE,
	TO_CHAR(
	NVL((SALARY+(SALARY*BONUS))*12, SALARY*12),
	'L999,999,999') AS "연봉(원)"
FROM EMPLOYEE;

-- 6번 문제
SELECT EMP_ID, EMP_NAME, DEPT_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D5'
	OR DEPT_CODE = 'D9')
	AND EXTRACT(YEAR FROM HIRE_DATE) = 2004;
	
-- 7번 문제
SELECT EMP_NAME, HIRE_DATE,
	(LAST_DAY(HIRE_DATE)-HIRE_DATE+1) AS "입사한 달의 근무 일수"
FROM EMPLOYEE;

-- 8번 문제
SELECT EMP_NAME, DEPT_CODE, 
	TO_CHAR(TO_DATE(LPAD(EMP_NO, 6), 'RRMMDD'),
	'YY')||'년 '||
	TO_CHAR(TO_DATE(LPAD(EMP_NO, 6), 'RRMMDD'),
	'MM')||'월 '||
	TO_CHAR(TO_DATE(LPAD(EMP_NO, 6), 'RRMMDD'),
	'DD')||'일 ' AS "생년월일",
	TRUNC(TRUNC(SYSDATE-TO_DATE(LPAD(EMP_NO, 6), 'RRMMDD'))/365)
	AS "만 나이"
FROM EMPLOYEE;