-- 문제 1번
SELECT STUDENT_SSN 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY 3;

-- 문제 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 문제 3번(미완)
SELECT PROFESSOR_NAME 교수이름,
	SYSDATE-TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) IN ('1', '3')
ORDER BY 2;

-- 문제 4번
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) 이름
FROM TB_PROFESSOR;

-- 문제 5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
	- EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) >= 20;
	
-- 문제 6번
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY')
FROM DUAL;

-- 문제 7번(미완)

-- 문제 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 문제 9번
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
WHERE STUDENT_NO LIKE 'A517178';

-- 문제 10번
SELECT DEPARTMENT_NO "학과번호", COUNT(*) "학생수(명)"
FROM TB_DEPARTMENT
NATURAL JOIN TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 문제 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 문제 12번(미완)
SELECT *
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
WHERE STUDENT_NO LIKE 'A112113';

-- 문제 13번(미완)
SELECT *
FROM TB_DEPARTMENT
NATURAL JOIN TB_STUDENT;

-- 문제 14번(미완)

-- 문제 15번(미완)
SELECT SUBSTR(TERM_NO, 1, 4) 년도,
	SUBSTR(TERM_NO, 5, 2) 학기, POINT 평점
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
WHERE STUDENT_NO LIKE 'A112113';