-- 문제 1번
SELECT STUDENT_NAME AS "학생 이름",
	STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1 ASC;

-- 문제 2번
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN LIKE 'N'
ORDER BY 2 DESC;

-- 문제 3번
SELECT STUDENT_NAME "학생이름",
STUDENT_NO "학번",
STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '%강원%'
OR STUDENT_ADDRESS LIKE '%경기%')
AND SUBSTR(STUDENT_NO, 1, 1) = '9'
ORDER BY 1;

-- 문제 4번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NAME LIKE '법학과'
ORDER BY 2;

-- 문제 5번(미완?)
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_CLASS
LEFT JOIN TB_STUDENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE TB_GRADE.TERM_NO = '200402'
AND TB_CLASS.CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1;

-- 문제 6번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
ORDER BY 2;

-- 문제 7번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 문제 8번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_PROFESSOR;

-- 문제 9번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 문제 10번(미완)
SELECT *
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME LIKE '음악학과';

-- 문제 11번
SELECT DEPARTMENT_NAME 학과이름,
	STUDENT_NAME 학생이름,
	PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
LEFT JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO LIKE 'A313047';

-- 문제 12번(미완)
SELECT *
FROM TB_STUDENT;

-- 문제 13번

-- 문제 14번
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE ASC;

-- 문제 15번(미완)
SELECT STUDENT_NAME
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NAME
HAVING AVG(POINT) > 4.0;

-- 문제 16번

-- 문제 17번
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
					   FROM TB_STUDENT
					   WHERE STUDENT_NAME = '최경희');

-- 문제 18번(미완)
SELECT *
FROM TB_STUDENT MAIN
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과';

-- 문제 19번