-- 문제 1번
SELECT STUDENT_NAME AS "학생 이름",
	STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1 ASC;

-- 문제 2번
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN LIKE 'N'
ORDER BY 2 DESC;

-- 문제 3번(미완)
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT;

-- 문제 4번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NAME LIKE '법학과'
ORDER BY 2;

-- 문제 5번

-- 문제 6번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
ORDER BY 2;

-- 문제 7번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 문제 8번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_PROFESSOR;

-- 문제 9번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
NATURAL JOIN TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 문제 10번(미완)
SELECT *
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME LIKE '음악학과';

-- 문제 11번
SELECT DEPARTMENT_NAME 학과이름,
	STUDENT_NAME 학생이름,
	PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
LEFT JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE STUDENT_NO LIKE 'A313047';

-- 문제 12번(미완)
SELECT *
FROM TB_STUDENT;

-- 문제 13번